// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using service.indumepi.Infra.Data;

#nullable disable

namespace service.indumepi.Infra.Data.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20241028134209_AddEstoq")]
    partial class AddEstoq
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("service.indumepi.Domain.Aggregates.Client.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CnpjCpf")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("CodigoCliente")
                        .HasColumnType("bigint");

                    b.Property<string>("NomeFantasia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Client");
                });

            modelBuilder.Entity("service.indumepi.Domain.Aggregates.Estoque.Estoque", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CCodigo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CDescricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("CodigoLocalEstoque")
                        .HasColumnType("bigint");

                    b.Property<int>("EstoqueMinimo")
                        .HasColumnType("int");

                    b.Property<int>("Fisico")
                        .HasColumnType("int");

                    b.Property<double>("NCMC")
                        .HasColumnType("float");

                    b.Property<long>("NCodProd")
                        .HasColumnType("bigint");

                    b.Property<int>("NPendente")
                        .HasColumnType("int");

                    b.Property<decimal>("NPrecoUnitario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("NSaldo")
                        .HasColumnType("int");

                    b.Property<int>("Reservado")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Estoque");
                });

            modelBuilder.Entity("service.indumepi.Domain.Aggregates.Family.Family", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CodFamilia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodInt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Codigo")
                        .HasColumnType("bigint");

                    b.Property<string>("Inativo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeFamilia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Families");
                });

            modelBuilder.Entity("service.indumepi.Domain.Aggregates.Item.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("CodigoFamilia")
                        .HasColumnType("bigint");

                    b.Property<long>("CodigoProduto")
                        .HasColumnType("bigint");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ValorUnitario")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Item");
                });

            modelBuilder.Entity("service.indumepi.Domain.Aggregates.Order.OrderList", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Cancelada")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("CodigoCliente")
                        .HasColumnType("bigint");

                    b.Property<long?>("CodigoEmpresa")
                        .HasColumnType("bigint");

                    b.Property<long?>("CodigoPedido")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DtPrevisao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Encerrado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Etapa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroPedido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("OrderList");
                });

            modelBuilder.Entity("service.indumepi.Domain.Aggregates.Order.OrderProduct", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Cfop")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CnpjFabricante")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Codigo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("CodigoCliente")
                        .HasColumnType("bigint");

                    b.Property<long>("CodigoEmpresa")
                        .HasColumnType("bigint");

                    b.Property<long>("CodigoProduto")
                        .HasColumnType("bigint");

                    b.Property<long>("CodigoTabelaPreco")
                        .HasColumnType("bigint");

                    b.Property<long?>("Conferencia")
                        .HasColumnType("bigint");

                    b.Property<long>("Conferido")
                        .HasColumnType("bigint");

                    b.Property<string>("Ean")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Editado")
                        .HasColumnType("bit");

                    b.Property<long?>("Enviado")
                        .HasColumnType("bigint");

                    b.Property<string>("Etapa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IndicadorEscala")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MotivoIcmsDesonerado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ncm")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroPedido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("PercentualDesconto")
                        .HasColumnType("bigint");

                    b.Property<long>("PrimeiraSeparacao")
                        .HasColumnType("bigint");

                    b.Property<long?>("Quantidade")
                        .HasColumnType("bigint");

                    b.Property<string>("Reservado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("SegundaSeparacao")
                        .HasColumnType("bigint");

                    b.Property<string>("TipoDesconto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Unidade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("ValorDeducao")
                        .HasColumnType("bigint");

                    b.Property<long?>("ValorDesconto")
                        .HasColumnType("bigint");

                    b.Property<long?>("ValorIcmsDesonerado")
                        .HasColumnType("bigint");

                    b.Property<long?>("ValorMercadoria")
                        .HasColumnType("bigint");

                    b.Property<long?>("ValorTotal")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("ValorUnitario")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("OrderProduct");
                });
#pragma warning restore 612, 618
        }
    }
}
