// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using service.indumepi.Infra.Data;

#nullable disable

namespace service.indumepi.Infra.Data.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("service.indumepi.Domain.Aggregates.Client.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CnpjCpf")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("CodigoCliente")
                        .HasColumnType("bigint");

                    b.Property<string>("NomeFantasia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Client");
                });

            modelBuilder.Entity("service.indumepi.Domain.Aggregates.Family.Family", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CodFamilia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodInt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Codigo")
                        .HasColumnType("bigint");

                    b.Property<string>("Inativo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeFamilia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Families");
                });

            modelBuilder.Entity("service.indumepi.Domain.Aggregates.Item.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("CodigoFamilia")
                        .HasColumnType("bigint");

                    b.Property<long>("CodigoProduto")
                        .HasColumnType("bigint");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ValorUnitario")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Item");
                });

            modelBuilder.Entity("service.indumepi.Domain.Aggregates.Order.OrderList", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Cancelada")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("CodigoCliente")
                        .HasColumnType("bigint");

                    b.Property<long>("CodigoEmpresa")
                        .HasColumnType("bigint");

                    b.Property<long>("CodigoPedido")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DtPrevisao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Encerrado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Etapa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroPedido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("OrderList");
                });

            modelBuilder.Entity("service.indumepi.Domain.Aggregates.Order.OrderProduct", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Cfop")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CnpjFabricante")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("CodigoCliente")
                        .HasColumnType("bigint");

                    b.Property<long>("CodigoEmpresa")
                        .HasColumnType("bigint");

                    b.Property<long>("CodigoProduto")
                        .HasColumnType("bigint");

                    b.Property<long>("CodigoTabelaPreco")
                        .HasColumnType("bigint");

                    b.Property<long>("Conferencia")
                        .HasColumnType("bigint");

                    b.Property<long>("Conferido")
                        .HasColumnType("bigint");

                    b.Property<string>("Ean")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Enviado")
                        .HasColumnType("bigint");

                    b.Property<string>("Etapa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IndicadorEscala")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MotivoIcmsDesonerado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ncm")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroPedido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("PercentualDesconto")
                        .HasColumnType("bigint");

                    b.Property<long>("PrimeiraSeparacao")
                        .HasColumnType("bigint");

                    b.Property<long>("Quantidade")
                        .HasColumnType("bigint");

                    b.Property<string>("Reservado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("SegundaSeparacao")
                        .HasColumnType("bigint");

                    b.Property<string>("TipoDesconto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Unidade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("ValorDeducao")
                        .HasColumnType("bigint");

                    b.Property<long>("ValorDesconto")
                        .HasColumnType("bigint");

                    b.Property<long>("ValorIcmsDesonerado")
                        .HasColumnType("bigint");

                    b.Property<long>("ValorMercadoria")
                        .HasColumnType("bigint");

                    b.Property<long>("ValorTotal")
                        .HasColumnType("bigint");

                    b.Property<decimal>("ValorUnitario")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("OrderProduct");
                });
#pragma warning restore 612, 618
        }
    }
}
